ALTER TABLE races ADD COLUMN IF NOT EXISTS elevation_loss_m INTEGER;
ALTER TABLE races ADD COLUMN IF NOT EXISTS min_elevation_m INTEGER;
ALTER TABLE races ADD COLUMN IF NOT EXISTS max_elevation_m INTEGER;
